on:
    workflow_dispatch:

jobs:
    grab-major:
        runs-on: ubuntu-latest
        outputs:
            major: ${{steps.grab_major.major}}
        steps:
            - run: echo "1.2.0" >> version.txt
            - id: grab_major
              run: echo "major=$(cat version.txt | cut -d. -f1)" >> $GITHUB_OUTPUT
    show-major:
        runs-on: ubuntu-latest
        needs: grab-major
        steps:
            - run: echo "${{needs.grab-major.outputs.major}}"